import {useEffect,useState} from "react";
const nav=["Dashboard","Monthly Cycle","Author","Book","Show","Novel","Series","N2A/A2A","UWT","Ledger","Exceptions","Rules","Historical Import","Calculation & QC"];
const sample=[["SHOW-10021","BOOK-20021","AUTH-30021","NOVEL",18425.5,"SUCCESS"],["SHOW-10022","BOOK-20022","AUTH-30022","SERIES",12840,"FAILED"],["SHOW-10023","BOOK-20023","AUTH-30023","N2A/A2A",9210.25,"REVERSED"]];
export default function App(){
 const[page,setPage]=useState("Dashboard"),[api,setApi]=useState("checking"),[month,setMonth]=useState("August 2026"),[view,setView]=useState("All");
 const[file,setFile]=useState<File|null>(null),[backfill,setBackfill]=useState(false),[result,setResult]=useState<any>(null);
 const[inputs,setInputs]=useState({incentive:100,revenue_share:900,other:0,marketing:100,platform:0,cop:0,flat:0,recovery:0,adjustment:0,tds_rate:10}),[calc,setCalc]=useState<any>(null),[qc,setQc]=useState<any>(null);
 const[marketing,setMarketing]=useState(30),[cop,setCop]=useState(30),[threshold,setThreshold]=useState(100);
 useEffect(()=>{fetch("/api/health").then(r=>r.json()).then(()=>setApi("online")).catch(()=>setApi("offline"))},[]);
 const rows=sample.filter(r=>view==="All"||r[3]===view);
 const upd=(k:string,v:string)=>setInputs({...inputs,[k]:Number(v)});
 async function doCalc(){const r=await fetch("/api/calculate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...inputs,tds_rate:inputs.tds_rate/100})});setCalc(await r.json())}
 async function doQC(){const r=await fetch("/api/qc/run",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({author_id:"DEMO",content_type:"NOVEL",incentive:inputs.incentive,contract_rs:7,product_rs:7,bank_ok:true,pan_ok:true,previously_paid:false,recovery_double:false,adjustment_reason:true,payment_threshold:threshold,final_net:Number(calc?.net_payable||0)})});setQc(await r.json())}
 async function doBackfill(){if(!file)return;setBackfill(true);setResult(null);const fd=new FormData();fd.append("files",file);try{const r=await fetch("/api/historical/backfill",{method:"POST",body:fd});setResult(await r.json())}catch{setResult({error:"Backend offline"})}finally{setBackfill(false)}}
 return <div className="app"><aside className="sidebar"><div className="brand">Creator Payout<br/>Control Tower</div>{nav.map(x=><div key={x} className={x===page?"nav active":"nav"} onClick={()=>setPage(x)}>{x}</div>)}</aside><main className="main">
 {page==="Historical Import"?<><header><div><div className="eyebrow">PHASE 6</div><h1>Historical Master Backfill</h1><p>Seed authors, content mappings and payment history from processed workbooks.</p></div></header><section className="panel"><h2>Upload historical workbook</h2><p className="muted">Use this for May-August processed files. Raw source files remain untouched; backfill creates normalized history.</p><input type="file" accept=".xlsx,.xlsm" onChange={e=>setFile(e.target.files?.[0]??null)}/><div className="uploadRow"><span>{file?.name||"No file selected"}</span><button disabled={!file||backfill} onClick={doBackfill}>{backfill?"Backfilling...":"Run Historical Backfill"}</button></div>{result&&<pre className="result">{JSON.stringify(result,null,2)}</pre>}</section></>
 :page==="Calculation & QC"?<><header><div><div className="eyebrow">PHASE 4/6</div><h1>Calculation & QC</h1><p>Transparent calculations with mandatory QC and adjustable caps.</p></div></header><section className="grid2"><div className="panel"><h2>Payout Calculation</h2>{Object.entries(inputs).map(([k,v])=><label key={k}>{k.replaceAll("_"," ")}<input value={v} onChange={e=>upd(k,e.target.value)}/></label>)}<button onClick={doCalc}>Calculate</button>{calc&&<pre className="result">{JSON.stringify(calc,null,2)}</pre>}</div><div className="panel"><h2>Rules & QC</h2><label>Marketing Cap %<input value={marketing} onChange={e=>setMarketing(Number(e.target.value))}/></label><label>COP Cap %<input value={cop} onChange={e=>setCop(Number(e.target.value))}/></label><label>Payment Threshold<input value={threshold} onChange={e=>setThreshold(Number(e.target.value))}/></label><button disabled={!calc} onClick={doQC}>Run Mandatory QC</button>{qc&&<pre className="result">{JSON.stringify(qc,null,2)}</pre>}</div></section></>
 :<><header><div><div className="eyebrow">PHASE 6 LOCAL PREVIEW</div><h1>Payment Operations</h1><p>Historical foundation, UWT processing, calculation and ledger controls.</p></div><div className="controls"><select value={month} onChange={e=>setMonth(e.target.value)}><option>August 2026</option><option>July 2026</option><option>June 2026</option><option>May 2026</option></select><select value={view} onChange={e=>setView(e.target.value)}><option>All</option><option>NOVEL</option><option>SERIES</option><option>N2A/A2A</option></select></div></header><section className="cards">{[["Ready for Payout","2,341"],["On Hold","145"],["Gross","₹52.44M"],["Net Payable","₹21.18M"],["Success","2,301"],["Retry Pool","40"]].map(([a,b])=><div className="card" key={a}><span>{a}</span><strong>{b}</strong></div>)}</section><section className="panel"><div className="panelHead"><div><h2>Show-Level Payment Ledger</h2><p>{month} · {view}</p></div><span className="health">API {api}</span></div><table><thead><tr><th>Show ID</th><th>Book ID</th><th>Author ID</th><th>Type</th><th>Net</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}><td>{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td><td>{r[3]}</td><td>₹{Number(r[4]).toLocaleString("en-IN",{minimumFractionDigits:2})}</td><td><span className={"pill "+r[5].toLowerCase()}>{r[5]}</span></td></tr>)}</tbody></table></section></>}</main></div>
}
