import {useEffect,useState} from "react";
const NAV=["Dashboard","Monthly Cycle","Payout","Novel","Series","N2A/A2A","UWT","Ledger","Exceptions","Rules","Author","Book","Show","Historical Import","Calculation & QC"];
const typeFor=(p)=>p==="Novel"?"NOVEL":p==="Series"?"SERIES":p==="N2A/A2A"?"N2A/A2A":undefined;

function Drill({kind,id,setPage,month}){
 const [data,setData]=useState(null);
 useEffect(()=>{if(!id)return;fetch(`/api/${kind}/${encodeURIComponent(id)}/360?period=${encodeURIComponent(month)}`).then(r=>r.json()).then(setData).catch(()=>setData(null))},[kind,id,month]);
 return <section className="panel"><div className="panelHead"><div><h2>{kind==="author"?"Author":"Content"} 360</h2><p>{id}</p></div><button onClick={()=>setPage(kind==="author"?"Author":"Show")}>Back</button></div><pre className="result">{JSON.stringify(data,null,2)}</pre></section>
}

export default function App(){
 const[page,setPage]=useState("Dashboard"),[month,setMonth]=useState("August 2026"),[api,setApi]=useState("checking");
 const[rows,setRows]=useState<any[]>([]),[summary,setSummary]=useState<any>(null),[exceptions,setExceptions]=useState<any[]>([]);
 const[inc,setInc]=useState<File|null>(null),[rs,setRs]=useState<File|null>(null),[processing,setProcessing]=useState(false),[run,setRun]=useState<any>(null),[validation,setValidation]=useState<any>(null);
 const[selected,setSelected]=useState<{kind:string,id:string}|null>(null);
 useEffect(()=>{fetch("/api/health").then(r=>r.json()).then(()=>setApi("online")).catch(()=>setApi("offline"))},[]);
 useEffect(()=>{if(["Dashboard","Novel","Series","N2A/A2A","Ledger"].includes(page))loadLedger();if(page==="Exceptions")loadExceptions()},[page,month]);
 async function loadLedger(){const t=typeFor(page);const url=t?`/api/ledger?month=${encodeURIComponent(month)}&content_type=${encodeURIComponent(t)}`:`/api/ledger?month=${encodeURIComponent(month)}`;const a=await fetch(url).then(r=>r.json()).catch(()=>[]);const b=await fetch(`/api/month/breakdown?month=${encodeURIComponent(month)}`).then(r=>r.json()).catch(()=>null);setRows(Array.isArray(a)?a:[]);setSummary(b)}
 async function loadExceptions(){setExceptions(await fetch(`/api/exceptions?period=${encodeURIComponent(month)}`).then(r=>r.json()).catch(()=>[]))}
 async function process(){if(!inc||!rs)return;setProcessing(true);setRun(null);setValidation(null);const fd=new FormData();fd.append("incentive_dump",inc);fd.append("revenue_share_dump",rs);try{const r=await fetch(`/api/monthly/process-two-dumps?period=${encodeURIComponent(month)}`,{method:"POST",body:fd});const d=await r.json();setRun(d);const v=await fetch(`/api/validation/month/${encodeURIComponent(month)}`).then(x=>x.json()).catch(()=>null);setValidation(v);await loadLedger()}finally{setProcessing(false)}}
 const download=(path)=>window.open(path,"_blank");const stats=summary?.status||{};
 return <div className="app"><aside className="sidebar"><div className="brand">Creator Payout<br/>Control Tower</div>{NAV.map(x=><div key={x} className={x===page?"nav active":"nav"} onClick={()=>{setPage(x);setSelected(null)}}>{x}</div>)}</aside><main className="main">
 <header><div><div className="eyebrow">LOCAL DEVELOPMENT · API {api}</div><h1>{page}</h1><p>{month}</p></div><select value={month} onChange={e=>setMonth(e.target.value)}><option>August 2026</option><option>July 2026</option><option>June 2026</option><option>May 2026</option></select></header>
 {selected?<Drill kind={selected.kind} id={selected.id} setPage={setPage} month={month}/>:null}
 {!selected&&page==="Monthly Cycle"&&<><section className="panel"><h2>Monthly two-dump processing</h2><p>Upload Incentive Dump and Revenue Share Dump for the same month. The system persists the source and runs QC.</p><div className="uploadGrid"><label>Incentive Dump<input type="file" accept=".xlsx,.xlsm" onChange={e=>setInc(e.target.files?.[0]||null)}/></label><label>Revenue Share Dump<input type="file" accept=".xlsx,.xlsm" onChange={e=>setRs(e.target.files?.[0]||null)}/></label></div><button disabled={!inc||!rs||processing} onClick={process}>{processing?"Processing...":"Process Monthly Cycle"}</button></section>{run&&<><section className="cards">{[["Incentive Rows",run.input_summary?.incentive_rows||0],["RS Rows",run.input_summary?.revenue_share_rows||0],["Source Rows",run.input_summary?.total_source_rows||0],["QC Block",run.qc_summary?.BLOCK||0],["QC Review",run.qc_summary?.REVIEW||0],["Authors",run.author_level_rows?.length||0]].map(([a,b])=><div className="card" key={a}><span>{a}</span><strong>{b}</strong></div>)}</section><section className="panel"><div className="panelHead"><div><h2>Author-Level Result</h2><p>Every author amount retains source references.</p></div><div className="buttons"><button onClick={()=>download(`/api/monthly/author-level/export?period=${encodeURIComponent(month)}`)}>Export Author CSV</button><button onClick={()=>download(`/api/monthly/qc/export?period=${encodeURIComponent(month)}`)}>Export QC CSV</button></div></div><div className="tableWrap"><table><thead><tr><th>Author</th><th>Incentive</th><th>Revenue Share</th><th>Gross</th><th>Content</th><th>Sources</th></tr></thead><tbody>{(run.author_level_rows||[]).slice(0,300).map((r)=> <tr key={r.author_id} onDoubleClick={()=>setSelected({kind:"author",id:r.author_id})}><td>{r.author_id}</td><td>{r.incentive_gross}</td><td>{r.revenue_share_gross}</td><td>{r.gross}</td><td>{r.content_types}</td><td>{r.source_references}</td></tr>)}</tbody></table></div></section>{validation&&<section className="panel"><h2>QC Cross-Check: {validation.status}</h2><div className="checks">{validation.checks?.map(c=><div key={c.check}>[{c.status}] {c.check}</div>)}</div><div className="validationSummary"><span>Eligible Gross ₹{Number(validation.eligible_gross||0).toLocaleString("en-IN",{minimumFractionDigits:2})}</span><span>Blocking {validation.qc_blocking}</span><span>Review {validation.qc_review}</span></div></section>}</>}</>}
 {!selected&&["Dashboard","Novel","Series","N2A/A2A","Ledger"].includes(page)&&<><section className="cards">{[["Rows",rows.length],["Success",stats.SUCCESS?.count||0],["Failed",stats.FAILED?.count||0],["Reversed",stats.REVERSED?.count||0],["Unmatched",stats.UNMATCHED?.count||0],["Content Groups",Object.keys(summary?.content||{}).length]].map(([a,b])=><div className="card" key={a}><span>{a}</span><strong>{b}</strong></div>)}</section><section className="panel"><h2>Show-Level Ledger</h2><div className="tableWrap"><table><thead><tr><th>Show ID</th><th>Book ID</th><th>Author ID</th><th>Content</th><th>Net</th><th>Status</th><th>Ledger</th><th>UTR</th></tr></thead><tbody>{rows.slice(0,500).map((r)=><tr key={r.payment_id}><td onDoubleClick={()=>r.show_id&&setSelected({kind:"content",id:r.show_id})}>{r.show_id||"-"}</td><td onDoubleClick={()=>r.book_id&&setSelected({kind:"content",id:r.book_id})}>{r.book_id||"-"}</td><td onDoubleClick={()=>r.author_id&&setSelected({kind:"author",id:r.author_id})}>{r.author_id||"-"}</td><td>{r.content_type}</td><td>{r.amount_after_tax==null?"-":"₹"+Number(r.amount_after_tax).toLocaleString("en-IN",{minimumFractionDigits:2})}</td><td><span className={"pill "+String(r.status).toLowerCase()}>{r.status}</span></td><td>{r.ledger_state}</td><td>{r.utr||"-"}</td></tr>)}</tbody></table></div></section></>}
 {!selected&&page==="Exceptions"&&<section className="panel"><h2>Exception Queue · {exceptions.length}</h2>{exceptions.length===0?<p>No open exceptions.</p>:<table><thead><tr><th>Rule</th><th>Severity</th><th>Entity</th><th>Message</th></tr></thead><tbody>{exceptions.map((x,i)=><tr key={i}><td>{x.rule_id}</td><td>{x.severity}</td><td>{x.entity_type}/{x.entity_id}</td><td>{x.message}</td></tr>)}</tbody></table>}</section>}
 {!selected&&page==="Rules"&&<section className="panel"><h2>Effective Rules</h2><p>Marketing, COP and payment threshold remain configurable and effective-dated.</p></section>}
 {!selected&&page==="UWT"&&<section className="panel"><h2>UWT Finance Result</h2><p>Import and export fixed 13-column UWT through the backend.</p><a href="/docs" target="_blank">Open API Docs</a></section>}
 {!selected&&page==="Historical Import"&&<section className="panel"><h2>Historical Backfill</h2><p>Stage previous processed months while preserving provenance.</p></section>}
 {!selected&&page==="Calculation & QC"&&<section className="panel"><h2>Calculation + Mandatory QC</h2><p>Calculation, configurable caps, batch QC and freeze controls are available in the backend.</p><a href="/docs" target="_blank">Open API Docs</a></section>}
 {!selected&&["Author","Book","Show"].includes(page)&&<section className="panel"><h2>{page} Explorer</h2><p>Double-click an Author, Book or Show in an output table to open its 360-degree source-backed view.</p></section>}
  
 {page==="Payout"&&<section className="panel"><h2>Author Payout Control</h2><p>Preview uses persisted source controls before batch creation.</p><div className="ruleGrid"><label>Marketing Cap %<input type="number" defaultValue="30"/></label><label>COP Cap %<input type="number" defaultValue="30"/></label><label>TDS Override %<input type="number" placeholder="Use PAN master"/></label></div><p className="muted">Next action is to calculate, run line QC, and freeze only after all required controls pass.</p><a href="/docs" target="_blank">Open API Docs</a></section>}
</main></div>
}